# permalink pattern
permalink: /:categories/:year-:month-:day-:title.html

# display settings
title: Murtaza Gulamali
tagline: software engineer
author:
  name: MYG

# global settings
encoding: UTF-8
exclude: [Gemfile, Gemfile.lock, LICENSE, Rakefile, README.md]
timezone: Europe/London
markdown: redcarpet

# jekyll-picture-tag settings
picture:
  source: "assets/img/_original"
  output: "assets/img/"
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5]
      source_small:
        media: "(max-width: 20em)"
        width: "320"
      source_medium:
        media: "(max-width: 30em)"
        width: "480"
      source_default:
        width: "640"
